### ISSUE TITLE
Basic build.sbt

### ISSUE THREAD

**Issue by yuriyzubarev** [earldouglas/xsbt-web-plugin#24]
Hi,

Can somebody provide basic build.sbt that works with sbt 0.10.1 and this plug-in? Whatever I do I cannot pass:

`error: value github is not a member of package com
seq(com.github.siasia.WebPlugin.webSettings :_*)`

My build.sbt:

```

scalaVersion := "2.9.0.1"

resolvers ++= Seq(
  "Sonatype Nexus Releases" at "https://oss.sonatype.org/content/repositories/releases",
  "Web plugin repo" at "http://siasia.github.com/maven2",
  Resolver.url("Typesafe repository", new java.net.URL("http://typesafe.artifactoryonline.com/typesafe/ivy-releases/"))(Resolver.defaultIvyPatterns)
)

libraryDependencies ++= Seq(
  "org.scalatra" %% "scalatra" % "2.0.0.M4",
  "org.scalatra" %% "scalatra-scalatest" % "2.0.0.M4",
  "org.mortbay.jetty" % "jetty" % "6.1.22" % "test",
  "org.mortbay.jetty" % "servlet-api" % "2.5-20081211" % "provided",
  "org.apache.solr" % "solr-solrj" % "3.3.0" % "test",
  "org.apache.solr" % "solr-core" % "3.3.0" % "test",
  "commons-codec" % "commons-codec" % "1.5"
)

libraryDependencies <+= sbtVersion(v => "com.github.siasia" %% "xsbt-web-plugin" % ("0.1.1-"+v))

seq(com.github.siasia.WebPlugin.webSettings :_*)
```

Looks like xsbt-web-plugin dependency is not being resolved. http://siasia.github.com/maven2 cannot be browsed, might be related, or it simply might not show a list of files/folders, so I'm not sure.

Thank you!
